import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import Navbar from "-/app/_componates/Navbar/Navbar";
import Footer from "-/app/_componates/Footer/Footer";
import Link from "next/link";
import { FaPhoneAlt } from "react-icons/fa";
import { MdEmail } from "react-icons/md";
import { IoPersonAdd, IoPersonSharp } from "react-icons/io5";
import { Toaster } from "sonner";
import WrapperForSessionProvider from "./_componates/WrapperForSessionProvider/WrapperForSessionProvider";
import Header from "./_componates/Header/Header";
import CartContextProvider from "./_context/cartContext";
import { getUserCart } from "-/api/services/route.services";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const res = await getUserCart();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContextProvider res={res}>
          <WrapperForSessionProvider>
            <Header />
            <Navbar />
            <Toaster />
            {children}
            <Footer />
          </WrapperForSessionProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
