import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "-/app/_componates/Navbar/Navbar";
import Footer from "-/app/_componates/Footer/Footer";
import Link from "next/link";
import { FaPhoneAlt } from "react-icons/fa";
import { MdEmail } from "react-icons/md";
import { IoPersonAdd, IoPersonSharp } from "react-icons/io5";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between px-5 py-3">
          <div className="flex gap-1">
            <h6>Free on orders 500 EGP</h6>
            <h6>new Arrivals daily</h6>
          </div>

          <div className="flex gap-2">
            <a href="#" className="flex gap-2 items-center">
              {" "}
              <FaPhoneAlt />
              (800) 123-456
            </a>
            <a href="#" className="flex gap-2 items-center">
              <MdEmail /> support@freschcart.com
            </a>
            <Link href="/login" className="flex gap-2 items-center">
              <IoPersonAdd /> Sign in
            </Link>
            <Link href="/register" className="flex gap-2 items-center">
              <IoPersonSharp /> Sign up
            </Link>
          </div>
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
